#redis
spring:
  jmx:
    enabled: false
  redis:
    host: 101.200.138.31
    port: 6379
    database: 0
    timeout: 1000  # 数据库连接超时时间，2.0 中该参数的类型为Duration，这里在配置的时候需要指明单位
    # 连接池配置，2.0中直接使用jedis或者lettuce配置连接池
    jedis:
      pool:
        # 最大空闲连接数
        max-idle: 500
        # 最小空闲连接数
        min-idle: 50
        # 等待可用连接的最大时间，负数为不限制
        max-wait: -1
        # 最大活跃连接数，负数为不限制
        max-active: -1
    password: 1234
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.200.138.31:3306/fmstore?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: Sunbo123.
ribbon:
  eager-load:
    enabled: true
    clients: service-portal #ribbon饥饿加载  多个服务逗号分离
  ReadTimeout: 60000
  ConnectTimeout: 60000
feign:
  sentinel:
    enabled: true
    # feign调用超时时间配置
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 600000